version: '2'
services:
  mongodb:
    image: mongo:4.2
    container_name: mongodb
    ports:
      - "27017:27017"
    expose:
      - "27017"

  weather-display-backend:
    image: docker-app-backend
    container_name: weather-display-backend
    ports:
      - "8080:8081"
    links:
      - mongodb

  weather-display-frontend:
    image: docker-app-frontend
    container_name: weather-display-frontend
    ports:
      - "4200:80"
    links:
      - weather-display-backend
